### ISSUE TITLE
Things required for this to replace the current wp-make yo generator 

### ISSUE THREAD

**Issue by saltcod** [magnificode/WPMakeOutput#10]
Wanted to create a placeholder for the conversation for how this theme could act as a complete replacement for the old yo generator. The current generator is great because it (mostly) puts everything in place for us — it sets up the enqueues, names the sass and js files properly, etc.  

I'm wondering if this theme can be made to work the same way. If we frontenders feel like it already does, it would be cool to get some backenders to go through the setup process as well — as they often end up doing theme setup at the start of projects.

**Comment by magnificode** [comment]
Agreed her as well, perhaps we could loop in @lkwdwrd and see what steps need to be taken to get that started.

**Comment by saltcod** [comment]
I need to test a few more things here but I think just having a one-word
name for the the would work.

That would reduce the effort to just 3 steps: rename the folder and do two
case sensitive find/replace. “Megatron” and “megatron”. I’m assuming the
name of this will obviously be megatron!

**Comment by timwright12** [comment]
I'm cool with megatron.

**Comment by saltcod** [comment]
Been thinking more about this one lately. Is this something we can move forward with? 

A few issues:

— Renaming all the things is a bit of a pain that something like "Megatron"/"megatron" would solve
— This repo has a readme and the theme folder at the root. I get why but makes using this whole repo as the theme a bit of a hassle.

**Comment by timwright12** [comment]
I think the consistency of the naming would be more important than the name itself, but yeah, as long as the steps are documented, easy, and BE is cool with it 👍

**Comment by saltcod** [comment]
>  I get why but makes using this whole repo as the theme a bit of a hassle.

I was wrong about this actually.  You can drop this whole repo's folder right in /themes/ and it works just fine.

**Comment by magnificode** [comment]
@saltcod that would be awesome, I'm all for anything that simplifies the search and replace process. I'm sad you didn't choose like...Star Wars character names. V1 as Anakin would be pretty cool, but I digress.

#20 relates to this issue as well, if you have time to make a PR with an updated theme name, some documentation in the README for the theme with what needs to be find and replaced would be awesome.

**Comment by saltcod** [comment]
Perfect.  I'll see if I can whip up a Star Wars infused theme asap!     =)

On Tue, Jan 30, 2018 at 2:00 PM, Dominic Magnifico <notifications@github.com

**Comment by magnificode** [comment]
Handled and merged by #23
