### ISSUE TITLE
CSS looks to be combining but not _combining_ 

### ISSUE THREAD

**Issue by saltcod** [magnificode/WPMakeOutput#2]
Styles do compile, but not quite perfectly: 

https://dl.dropboxusercontent.com/s/83tuha4wt49wrq9/2017-08-01%20at%203.39%20PM.png

It's concat-ing things, but isn't handling the imports. 

Hillary Shrug!

**Comment by magnificode** [comment]
@saltcod are you still seeing this issue by chance? I've pulled down the repo on a new project and the `@import`'s seem to be properly compiling.

**Comment by saltcod** [comment]
aha!  Indeed. Just grabbed the latest and seems to work as expected. Highfive! 

https://dl.dropboxusercontent.com/s/c7s4n3fsnh7l7j6/2017-09-11%20at%207.28%20AM.png
