### ISSUE TITLE
Ensure JavaScript compiles both a non minified and minified file

### ISSUE THREAD

**Issue by magnificode** [magnificode/WPMakeOutput#3]
Non minified should not be placed in the dist folder.

**Comment by timwright12** [comment]
Did we have a side conversation about all compiled assets being in /dist? That would be my preference, but if I'm out voted, totally cool, but lets make sure it gets into the .gitignore so we avoid merge conflicts.

Ignore/close out if this is a stale issue.

**Comment by magnificode** [comment]
We have established that sourcemaps are well enough implemented that a non minified JS file isn't necessary. Closing this out for now.
